/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doom119_ffs_Loader */

#ifndef _Included_com_doom119_ffs_FFMPEG
#define _Included_com_doom119_ffs_FFMPEG
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_com_doom119_ffs_FFMPEG_init
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL
Java_com_doom119_ffs_FFMPEG_open(JNIEnv *env, jclass clazz, jstring videoPath);

JNIEXPORT void JNICALL
Java_com_doom119_ffs_FFMPEG_close(JNIEnv *env, jclass clazz);

JNIEXPORT jint JNICALL
Java_com_doom119_ffs_FFMPEG_decode(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
