/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doom119_ffs_Loader */

#ifndef _Included_com_doom119_ffs_Loader
#define _Included_com_doom119_ffs_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doom119_ffs_Loader
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_doom119_ffs_FFS_init
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL
Java_com_doom119_ffs_FFS_open(JNIEnv *env, jclass clazz, jstring videoPath);

JNIEXPORT void JNICALL
Java_com_doom119_ffs_FFS_close(JNIEnv *env, jclass clazz);

JNIEXPORT jint JNICALL
Java_com_doom119_ffs_FFS_decode(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
